version: "3.8"

services:
   papermc:
     # Change container_name to desired name.
     container_name: papermc
     hostname: papermc
     image: tracedgod/papermc:latest
     # For docker attach functionality, both stdin_open and tty must be set to true.
     stdin_open: true
     tty: true
     ports:
      # - '8123:8123/tcp'        # Dynmaps webserver port
      # If you are using Geyser + Floodgate, uncomment both '19132' ports
      # - '19132:19132/tcp'
      # - '19132:19132/udp'
       - '25565:25565/tcp'
      # - '25575:25575/tcp'      # Server RCON port
     environment:
       # Change below env variables to desired values, default for MC_VERSION + PAPER_BUILD is latest, MC_RAM + JAVA_OPTS are optional.
       - MC_VERSION=latest
       - PAPER_BUILD=latest
       - MC_RAM=
       - JAVA_OPTS=
     restart: unless-stopped
     volumes:
      # Uncomment + Change this to server files path. For rw access on host, create a new group with GID 5000 and add yourself to said group.
      # - '<path-to-server-volume>:/papermc'
